//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlDiff.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HtmlDiff.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DIV class=&quot;e&quot; xmlns:fhir=&quot;http://hl7.org/fhir&quot;&gt;&lt;DIV class=&quot;c&quot; STYLE=&quot;margin-left:1em;text-indent:-2em&quot;&gt;&lt;span class=&quot;b&quot;&gt; &lt;/span&gt; &lt;SPAN class=&quot;m&quot;&gt;&amp;lt;&lt;/SPAN&gt;&lt;SPAN class=&quot;t&quot;&gt;entry&lt;/SPAN&gt; &lt;SPAN class=&quot;m&quot;&gt;&amp;gt;&lt;/SPAN&gt;&lt;/DIV&gt;&lt;DIV&gt;
        ///	  &lt;DIV class=&quot;e&quot;&gt;&lt;DIV STYLE=&quot;margin-left:1em;text-indent:-2em&quot;&gt;&lt;SPAN class=&quot;b&quot;&gt; &lt;/SPAN&gt;&lt;SPAN class=&quot;m&quot;&gt;&amp;lt;&lt;/SPAN&gt;&lt;SPAN class=&quot;t&quot;&gt;fullUrl&lt;/SPAN&gt;&lt;SPAN class=&quot;t&quot;&gt;value&lt;/SPAN&gt;&lt;SPAN class=&quot;m&quot;&gt;=&quot;&lt;/SPAN&gt;&lt;B&gt;https://localhost:44346/fhir/Questionnaire/demo-scoring/_history/8&lt;/B&gt;&lt;SPAN class=&quot;m&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DIV class=&quot;e&quot; xmlns:fhir=&quot;http://hl7.org/fhir&quot;&gt;&lt;DIV class=&quot;c&quot; STYLE=&quot;margin-left:1em;text-indent:-2em&quot;&gt;&lt;span class=&quot;b&quot;&gt; &lt;/span&gt; &lt;SPAN class=&quot;m&quot;&gt;&amp;lt;&lt;/SPAN&gt;&lt;SPAN class=&quot;t&quot;&gt;entry&lt;/SPAN&gt; &lt;SPAN class=&quot;m&quot;&gt;&amp;gt;&lt;/SPAN&gt;&lt;/DIV&gt;&lt;DIV&gt;
        ///	  &lt;DIV class=&quot;e&quot;&gt;&lt;DIV STYLE=&quot;margin-left:1em;text-indent:-2em&quot;&gt;&lt;SPAN class=&quot;b&quot;&gt; &lt;/SPAN&gt;&lt;SPAN class=&quot;m&quot;&gt;&amp;lt;&lt;/SPAN&gt;&lt;SPAN class=&quot;t&quot;&gt;fullUrl&lt;/SPAN&gt;&lt;SPAN class=&quot;t&quot;&gt;value&lt;/SPAN&gt;&lt;SPAN class=&quot;m&quot;&gt;=&quot;&lt;/SPAN&gt;&lt;B&gt;https://localhost:44346/fhir/Questionnaire/demo-scoring/_history/7&lt;/B&gt;&lt;SPAN class=&quot;m&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
    }
}
